// src/components/Navbar.vue
<template>
  <nav class="container-fluid">
    <ul>
      <img src="../assets/Bowl.png" alt="bowl" style="width: 50px" />
      <li><strong>MealPad</strong></li>
    </ul>
    <ul class="items-center gap-3 hidden sm:flex">
      <li>
        <router-link to="/" class="contrast"> Home </router-link>
      </li>
      <li>
        <router-link to="/search" class="contrast"> Search </router-link>
      </li>
      <li>
        <router-link to="/favorite" class="contrast"> Favorites </router-link>
      </li>
    </ul>
  </nav>
</template>

<style scoped>
navs {
  background-color: hsla(0, 0%, 0%, 0.1);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid hsla(0, 0%, 50%, 0.1);
}

strong {
  color: var(--contrast);
}
</style>

// src/components/navbar.tsx
import { useState } from 'react';
import MenuIcon from '../assets/icon/menu-1.svg'
import { Link } from 'react-router-dom';
const Navbar = () => {
  const [sidebarActive, setSidebarActive] = useState();

  return (
    <nav className='p-6 flex justify-between sticky top-0 bg-white z-1 '>
      <Link to={'/'} className='flex items-center gap-2 cursor-pointer'>
        <img
          className='h-8'
          src='/bowl.png'
          alt='Meal Pad Logo'
        />
        <span className='font-semibold font-sans text-xl'>Meal Pad</span>
      </Link>
      <div className='flex items-center'>
        <img src={MenuIcon} alt="mealpad menu" />
        {/* <ul className='absolute h-screen w-screen bg-amber top-0 right-0'>
          <li>
            <Link to={'/'}>Home</Link>
            <Link to={'/Search'}>Search</Link>
            <Link to={'/Search'}>Favorites</Link>
          </li>
        </ul> */}
      </div>
    </nav>
  );
}

export default Navbar;
